<?php
/**
 * Created by PhpStorm.
 * User: qiangbi
 * Date: 17-3-31
 * Time: 下午6:36
 */

namespace app\index\model;

use think\Model;
class Account extends Model
{
    public static function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        //写入操作时 获取role_name
        Account::event('before_write',function($account){
            $account->role_name=(\app\index\model\Role::where("id",$account->role)->value("name"));
        });
    }

}