<?php
/**
 * 权限模型
 * Created by PhpStorm.
 * User: qiangbi
 * Date: 17-3-11
 * Time: 下午4:03
 */
namespace app\index\model;

use think\Model;

class Privilege extends Model
{
    /**
     * initialize 初始化方法 处理事件
     */
//    public function initialize()
//    {
//        parent::initialize(); // TODO: Change the autogenerated stub
//        //前置插入操作
//        Privilege::event("before_insert", function ($privilege) {
//            if(!empty($privilege->parent_id)){
//                $parent_arr=$privilege->find($privilege->parent_id)->toArray();
//                $privilege->path=$parent_arr["path"].$privilege->parent_id.",";
//            }
//        });
//        //前置修改操作
//        Privilege::event("before_update",function($privilege){
//            $bfuData=$this->where(["id"=>$privilege->id])->find();
//            //两次id不一样说明修改了父节点
//            if($bfuData->parent_id!=$privilege->parent_id){
//                //如果parent_id是0的话,是修改为顶级节点
//                if($privilege->parent_id==0){
//                    $privilege->path=",";
////                    $this->
//                }
//            }
//
//        });
//    }

}